spring.application.name=demo

server.port=80

logging.pattern.dateformat=hh:mm
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.main.banner-mode=off
spring.thymeleaf.cache=false

#spring.datasource.url=jdbc:mysql://localhost:3306/techshop
spring.datasource.url=jdbc:mysql://avnadmin:AVNS_n_DN1GLgvBOiQC00iNb@techshop-techshop19.a.aivencloud.com:27711/techshop
spring.datasource.username=usuario_prueba
spring.datasource.password=Usuario_Clave.

#spring.jpa.properties.hibernate.format_sql=true

firebase.bucket.name=techshop-e3a1a.firebasestorage.app
firebase.storage.path=techshop
firebase.json.path=firebase
firebase.json.file=techshop-e3a1a-firebase-adminsdk-fbsvc-396a74fb24.json
